CREATE TABLE user (
	id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
	email VARCHAR(50) NOT NULL UNIQUE, 
	password_hash VARCHAR(64)  NOT NULL,
	total_amount DECIMAL  DEFAULT 0,
	pending_amount DECIMAL DEFAULT 0,
	total_expense DECIMAL DEFAULT 0
);